<?php
/**
 * const.php — engine + default configuration for the EVEmu portal.
 *
 * DO NOT edit this file for settings: it is replaced on every update.
 * Put your own values in config.php (git-ignored); every define here is guarded
 * with if(!defined(...)) so config.php always wins. Helper functions and the
 * session bootstrap live here.
 */

// ---- defaults (overridable from config.php) ---------------------------------
if (!defined('API_BASE'))      define('API_BASE', 'http://127.0.0.1:26002');
if (!defined('IMAGE_SERVER'))  define('IMAGE_SERVER', 'http://127.0.0.1:26001');
if (!defined('EVE_RENDER'))    define('EVE_RENDER', 'https://images.evetech.net/types');
if (!defined('EVE_ICON'))      define('EVE_ICON', 'https://images.evetech.net/types');
if (!defined('SITE_NAME'))     define('SITE_NAME', 'EVEmu');
if (!defined('PORTAL_VERSION')) define('PORTAL_VERSION', '1.0.0');
if (!defined('SESSION_LIFETIME')) define('SESSION_LIFETIME', 8 * 3600); // max 8 hours

// Web Push (see config.sample.php for the user-facing description)
if (!defined('PUSH_ENABLED'))       define('PUSH_ENABLED', false);
if (!defined('VAPID_PUBLIC_KEY'))   define('VAPID_PUBLIC_KEY', '');
if (!defined('VAPID_PRIVATE_KEY'))  define('VAPID_PRIVATE_KEY', '');
if (!defined('VAPID_SUBJECT'))      define('VAPID_SUBJECT', 'mailto:admin@' . (parse_url(API_BASE, PHP_URL_HOST) ?: 'localhost'));
if (!defined('PUSH_DATA_DIR'))      define('PUSH_DATA_DIR', __DIR__ . '/cache');

// outbound e-mail (SMTP)
if (!defined('MAIL_ENABLED'))    define('MAIL_ENABLED', false);
if (!defined('MAIL_HOST'))       define('MAIL_HOST', '');
if (!defined('MAIL_PORT'))       define('MAIL_PORT', 587);
if (!defined('MAIL_USER'))       define('MAIL_USER', '');
if (!defined('MAIL_PASS'))       define('MAIL_PASS', '');
if (!defined('MAIL_FROM'))       define('MAIL_FROM', '');
if (!defined('MAIL_FROM_NAME'))  define('MAIL_FROM_NAME', SITE_NAME);
if (!defined('MAIL_ENCRYPTION')) define('MAIL_ENCRYPTION', 'tls'); // tls | ssl | none
if (!defined('MAIL_TIMEOUT'))    define('MAIL_TIMEOUT', 30);

// two-factor e-mail codes
if (!defined('TFA_ENABLED'))           define('TFA_ENABLED', true);
if (!defined('TFA_REQUIRE_NEW_DEVICE')) define('TFA_REQUIRE_NEW_DEVICE', true);
if (!defined('TFA_ADMIN_ALWAYS'))      define('TFA_ADMIN_ALWAYS', true);
if (!defined('TFA_CODE_TTL'))          define('TFA_CODE_TTL', 10 * 60);
if (!defined('TFA_MAX_ATTEMPTS'))      define('TFA_MAX_ATTEMPTS', 5);
if (!defined('TFA_DEVICE_COOKIE'))     define('TFA_DEVICE_COOKIE', 'evemu_2fa_dev');
if (!defined('TFA_DEVICE_LIFETIME'))   define('TFA_DEVICE_LIFETIME', 180 * 24 * 3600);

// CCP account role bits (see eve-common/EVE_Roles.h Acct::Role)
if (!defined('ROLE_PLAYER'))     define('ROLE_PLAYER', 0);
if (!defined('ROLE_GML'))        define('ROLE_GML', 18014398509481984);
if (!defined('ROLE_GMH'))        define('ROLE_GMH', 9007199254740992);
if (!defined('ROLE_QA'))         define('ROLE_QA', 4503599627370496);
if (!defined('ROLE_WORLDMOD'))   define('ROLE_WORLDMOD', 4096);
if (!defined('ROLE_CENTURION'))  define('ROLE_CENTURION', 2048);
if (!defined('ROLE_ADMIN'))      define('ROLE_ADMIN', 72057594037927936);
if (!defined('ROLE_VIPLOGIN'))   define('ROLE_VIPLOGIN', 144115188075855872);
if (!defined('ROLE_CONTENT'))    define('ROLE_CONTENT', 36028797018963968);
if (!defined('ROLE_CHTADMIN'))   define('ROLE_CHTADMIN', 2097152);
if (!defined('ROLE_LEGIONEER'))  define('ROLE_LEGIONEER', 262144);

// ---- session bootstrap ------------------------------------------------------
if (PHP_SAPI !== 'cli' && session_status() === PHP_SESSION_NONE) {
    session_set_cookie_params([
        'lifetime' => SESSION_LIFETIME,
        'path'     => '/',
        'httponly' => true,
        'samesite' => 'Lax',
    ]);
    session_start();
    if (isset($_SESSION['login_time']) && time() - (int)$_SESSION['login_time'] > SESSION_LIFETIME) {
        session_unset();
        session_destroy();
    }
}

// ---- API helpers ------------------------------------------------------------
function api_get($path, $timeout = 5) {
    $url = API_BASE . $path;
    $ctx = stream_context_create(['http' => ['timeout' => $timeout]]);
    $data = @file_get_contents($url, false, $ctx);
    if ($data === false) return null;
    return @simplexml_load_string($data);
}

function api_post($path, $body = '', $timeout = 10) {
    $url = API_BASE . $path;
    $opts = ['http' => [
        'method' => 'POST',
        'header' => "Content-Type: application/x-www-form-urlencoded\r\n",
        'content' => $body,
        'timeout' => $timeout,
    ]];
    $ctx = stream_context_create($opts);
    $data = @file_get_contents($url, false, $ctx);
    if ($data === false) return null;
    return @simplexml_load_string($data);
}

// ---- auth/session helpers ---------------------------------------------------
function current_user() {
    if (isset($_SESSION['accountID']))
        return [
            'accountID' => $_SESSION['accountID'],
            'accountName' => $_SESSION['accountName'] ?? '',
            'role' => $_SESSION['role'] ?? 0,
        ];
    return null;
}

function is_logged_in() { return current_user() !== null; }

function has_role($bit) {
    $u = current_user();
    return $u && ($u['role'] & $bit);
}

function role_name($role) {
    $names = [];
    if ($role & ROLE_ADMIN)    $names[] = 'Admin';
    if ($role & ROLE_GMH)      $names[] = 'GMH';
    if ($role & ROLE_GML)      $names[] = 'GML';
    if ($role & ROLE_QA)       $names[] = 'QA';
    if ($role & ROLE_WORLDMOD) $names[] = 'WorldMod';
    if ($role & ROLE_CHTADMIN) $names[] = 'ChatAdmin';
    if (empty($names))         $names[] = 'Player';
    return implode(', ', $names);
}

// ---- image helpers ----------------------------------------------------------
function evetech_size($size) {
    $size = (int)$size;
    if ($size <= 48)  return 32;
    if ($size <= 96)  return 64;
    if ($size <= 192) return 128;
    if ($size <= 384) return 256;
    return 512;
}

function ship_icon($typeID, $size = 32) {
    if (!$typeID) return '';
    return '/img.php?url=' . urlencode(EVE_RENDER . '/' . $typeID . '/render?size=' . evetech_size($size));
}

function ship_type_icon($typeID, $size = 32) {
    if (!$typeID) return '';
    return '/img.php?url=' . urlencode(EVE_ICON . '/' . $typeID . '/icon?size=' . evetech_size($size));
}

// Portraits/logos live on OUR image server; browsers cannot reach a LAN 172.x
// address, so these go through the /img.php cache proxy.
function char_portrait($charID, $size = 64) {
    if (!$charID) return '';
    return '/img.php?url=' . urlencode(IMAGE_SERVER . '/Character/' . $charID . '_' . $size . '.jpg');
}

function corp_logo($corpID, $size = 32) {
    if (!$corpID) return '';
    return '/img.php?url=' . urlencode(IMAGE_SERVER . '/Corporation/' . $corpID . '_' . $size . '.png');
}

function alliance_logo($allianceID, $size = 32) {
    if (!$allianceID) return '';
    return '/img.php?url=' . urlencode(IMAGE_SERVER . '/Alliance/' . $allianceID . '_' . $size . '.png');
}

// ---- formatting helpers -----------------------------------------------------
function filetime_to_unix($filetime) {
    $ft = (int)$filetime;
    if ($ft <= 0) return 0;
    return intval(($ft - 116444736000000000) / 10000000);
}

function security_color($sec) {
    $sec = (float)$sec;
    if ($sec >= 0.5) return '#00ff00';
    if ($sec >= 0.0) return '#ffff00';
    if ($sec >= -0.5) return '#ff8800';
    if ($sec >= -0.8) return '#ff4400';
    return '#ff0000';
}

function redirect($url) {
    header("Location: $url");
    exit;
}

function e($s) { return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }

function time_ago($ts) {
    if ($ts <= 0) return '';
    $diff = time() - $ts;
    if ($diff < 0) return 'just now';
    if ($diff < 60) return $diff . 's ago';
    if ($diff < 3600) return floor($diff / 60) . 'm ago';
    if ($diff < 86400) return floor($diff / 3600) . 'h ago';
    return floor($diff / 86400) . 'd ago';
}

function format_isk($val) {    $val = (float)$val;
    if ($val >= 1e12) return number_format($val / 1e12, 2) . 'T ISK';
    if ($val >= 1e9) return number_format($val / 1e9, 2) . 'B ISK';
    if ($val >= 1e6) return number_format($val / 1e6, 2) . 'M ISK';
    if ($val >= 1e3) return number_format($val / 1e3, 2) . 'K ISK';
    return number_format($val, 2) . ' ISK';
}

// Compact EVE-ish money like "57.86b" / "1.05t" (dot decimal, no spaces).
function isk_compact($val) {
    $val = (float)$val;
    if ($val >= 1e12) return rtrim(rtrim(number_format($val / 1e12, 2, '.', ''), '0'), '.') . 't';
    if ($val >= 1e9)  return rtrim(rtrim(number_format($val / 1e9, 2, '.', ''), '0'), '.') . 'b';
    if ($val >= 1e6)  return rtrim(rtrim(number_format($val / 1e6, 2, '.', ''), '0'), '.') . 'm';
    if ($val >= 1e3)  return rtrim(rtrim(number_format($val / 1e3, 2, '.', ''), '0'), '.') . 'k';
    return number_format($val, 0, '.', '');
}

function format_isk_full($val) {
    return number_format((float)$val, 2) . ' ISK';
}

function get_slot_name($flag) {
    $flag = (int)$flag;
    // EVE item flags (EVE_Flags.h): Low 11-18, Mid 19-26, High 27-34, Rig 92-94/155,
    // SubSystem 125-133, Cargo 5, Drone Bay 87/89.
    if ($flag >= 11 && $flag <= 18) return 'Low';
    if ($flag >= 19 && $flag <= 26) return 'Mid';
    if ($flag >= 27 && $flag <= 34) return 'High';
    if ($flag >= 92 && $flag <= 94) return 'Rig';
    if ($flag === 155) return 'Rig';
    if ($flag >= 125 && $flag <= 133) return 'Subsystem';
    if ($flag === 87 || $flag === 89) return 'Drone Bay';
    if ($flag === 5 || $flag === 0 || $flag === 8) return 'Cargo';
    return 'Other';
}

function slot_sort_order($name) {
    $order = ['High' => 0, 'Mid' => 1, 'Low' => 2, 'Rig' => 3, 'Subsystem' => 4, 'Ship' => 5, 'Cargo' => 6, 'Drone Bay' => 7, 'Other' => 8];
    return $order[$name] ?? 9;
}

// Generic client-side pager for admin lists. Preserves the current GET params
// (except page) so filters/view stay active. $items is a full array; returns
// nothing when it fits on one page. $out/$page/$pages are by-reference outputs
// (passed possibly-uninitialised by callers).
function paginate_admin($items, $perPage, &$out, &$page, &$pages): void {
    $perPage = max(1, (int)$perPage);
    $items   = is_array($items) ? array_values($items) : [];
    $pages   = max(1, (int)ceil(count($items) / $perPage));
    $page    = isset($_GET['page']) && is_numeric($_GET['page']) ? (int)$_GET['page'] : 1;
    $page    = max(1, min($pages, $page));
    $out     = array_slice($items, ($page - 1) * $perPage, $perPage);
}

function pager_html(int $page, int $pages): string {
    if ($pages <= 1) return '';
    $path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?: '/';
    $q = $_GET;
    $html = '<div class="pagination" style="margin-top:10px">';
    if ($page > 1) { $q['page'] = $page - 1; $html .= '<a href="' . htmlspecialchars($path . '?' . http_build_query($q), ENT_QUOTES, 'UTF-8') . '">&larr; Prev</a>'; }
    $html .= '<span>' . $page . ' / ' . $pages . '</span>';
    if ($page < $pages) { $q['page'] = $page + 1; $html .= '<a href="' . htmlspecialchars($path . '?' . http_build_query($q), ENT_QUOTES, 'UTF-8') . '">Next &rarr;</a>'; }
    $html .= '</div>';
    return $html;
}

// ---- push subscription store (JSON file in PUSH_DATA_DIR) --------------------
function push_subs_file(): string {
    if (!is_dir(PUSH_DATA_DIR)) @mkdir(PUSH_DATA_DIR, 0775, true);
    return rtrim(PUSH_DATA_DIR, '/') . '/push_subs.json';
}

function push_subs(): array {
    $f = push_subs_file();
    if (!is_file($f)) return [];
    $raw = @file_get_contents($f);
    $arr = json_decode((string)$raw, true);
    return is_array($arr) ? $arr : [];
}

function push_save_subs(array $subs): void {
    // key by endpoint
    $byKey = [];
    foreach ($subs as $s) if (isset($s['endpoint'])) $byKey[$s['endpoint']] = $s;
    file_put_contents(push_subs_file(), json_encode(array_values($byKey), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE), LOCK_EX);
}

// base64url helpers (browser push keys are base64url, VAPID keys too)
function b64url_encode(string $data): string {
    return rtrim(strtr(base64_encode($data), '+/', '-_'), '=');
}
function b64url_decode(string $data): string {
    return base64_decode(strtr($data, '-_', '+/'));
}

// ---- client IP (works behind nginx / proxies) -------------------------------
function client_ip(): string {
    foreach (['HTTP_CF_CONNECTING_IP', 'HTTP_X_REAL_IP'] as $h) {
        if (!empty($_SERVER[$h]) && filter_var($_SERVER[$h], FILTER_VALIDATE_IP)) return $_SERVER[$h];
    }
    if (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
        foreach (explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']) as $ip) {
            $ip = trim($ip);
            if (filter_var($ip, FILTER_VALIDATE_IP)) return $ip;
        }
    }
    return $_SERVER['REMOTE_ADDR'] ?? '';
}

// ---- 2FA trusted devices (JSON store, per accountID) -------------------------
function tfa_devices_file(): string {
    if (!is_dir(PUSH_DATA_DIR)) @mkdir(PUSH_DATA_DIR, 0775, true);
    return rtrim(PUSH_DATA_DIR, '/') . '/tfa_devices.json';
}
function tfa_devices(): array {
    $f = tfa_devices_file();
    if (!is_file($f)) return [];
    $raw = json_decode((string)@file_get_contents($f), true);
    return is_array($raw) ? $raw : [];
}
function tfa_save_devices(array $all): void {
    // trim: drop devices idle > 90 days
    $cut = time() - TFA_DEVICE_LIFETIME;
    foreach ($all as $aid => $devs) {
        $all[$aid] = array_values(array_filter($devs, function ($d) use ($cut) {
            return (int)($d['last'] ?? 0) >= $cut;
        }));
        if (!$all[$aid]) unset($all[$aid]);
    }
    file_put_contents(tfa_devices_file(), json_encode($all, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE), LOCK_EX);
}
function tfa_device_token(): string {
    return (string)($_COOKIE[TFA_DEVICE_COOKIE] ?? '');
}
function is_staff_role($role): bool {
    $role = (int)$role;
    return (bool)($role & (ROLE_ADMIN | ROLE_GMH | ROLE_GML));
}
// Does this browser/IP need a code?
function tfa_requires_code(int $aid, $role, string $ip): bool {
    if (!TFA_ENABLED) return false;
    if (TFA_ADMIN_ALWAYS && is_staff_role($role)) return true;
    if (!TFA_REQUIRE_NEW_DEVICE) return false;
    $token = tfa_device_token();
    $devs = tfa_devices()[$aid] ?? [];
    if ($token === '') return true;             // new/unknown browser
    foreach ($devs as $d) {
        if (($d['token'] ?? '') === $token) {
            if (($d['ip'] ?? '') === $ip) return false;  // same device + same IP → trusted
            return true;                                  // same browser, new IP → code
        }
    }
    return true;
}
function tfa_trust_device(int $aid, string $ip): void {
    $all = tfa_devices();
    $devs = $all[$aid] ?? [];
    $token = tfa_device_token();
    if ($token === '') {
        $token = bin2hex(random_bytes(20));
        setcookie(TFA_DEVICE_COOKIE, $token, time() + TFA_DEVICE_LIFETIME, '/', '', !empty($_SERVER['HTTPS']), true);
    }
    foreach ($devs as $i => $d) {
        if (($d['token'] ?? '') === $token && ($d['ip'] ?? '') === $ip) { $devs[$i]['last'] = time(); $all[$aid] = $devs; tfa_save_devices($all); return; }
    }
    $devs[] = ['token' => $token, 'ip' => $ip, 'first' => time(), 'last' => time()];
    $all[$aid] = $devs;
    tfa_save_devices($all);
}
function tfa_new_code(): string {
    return sprintf('%06d', random_int(0, 999999));
}
